//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_AniTag
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sahipler
    {
        public int sahip_id { get; set; }
        public string sahip_adi { get; set; }
        public string sahip_tel { get; set; }
        public string sahip_tc { get; set; }
        public string sahip_mail { get; set; }
    }
}
